# syntax = docker/dockerfile:1
FROM node:alpine

# アプリケーションディレクトリを作成
WORKDIR /app

# アプリケーションの依存関係をコピー
COPY package*.json ./

# 依存関係をインストール
RUN npm install

# アプリケーションのソースをコピー
COPY . .

# ポート3000番を開放
EXPOSE 3000

# コンテナ起動時に実行するコマンド
CMD ["npm", "run", "dev"]